// SINGLY LINKED LIST : THE ONE WHICH WE HAVE BEEN USING TILL NOW....   NOTE : WHEN QUESTIONS ASKED ABOUT LINKED LIST...IT BY DEFAULT MEANS THIS ONE...UNLESS OTHERWISE MENTIONED

// DOUBLY LINKED LIST : EACH NODE HAS 1-DATA AND 2-NODE* ,,, ONE POINTING TO "NEXT", OTHER TO "PREVIOUS", HERE EACH NODE HOLDS ADDRESS OF BOTH NEXT AND PREVIOUS NODE... AND TRAVERSING IN BOTH DIRECTIONS IS POSSIBLE....UNLIKE SINGLY LINKED LIST WHERE WE HAD TO STRUGGLE COZ IT CAN MOVE ONLY IN ONE DIRECTION....
// CODING IS EASY USING "DOUBLY LL" BUT IT CONSUMES MORE SPACE!!  DON'T USE IT UNLESS EXPLICITLY MENTIONED

// CIRCULAR SINGLY LINKED LIST : THE LAST NODE DOES NOT HAVE NULL BUT THE ADDRESS OF THE FIRST NODE...THUS FORMING A CIRCULAR SINGLY LL         BENEFIT: WE DON'T HAVE TO MAINTAIN A "HEAD" .... EVEN IF WE KNOW ADDRESS OF ANY ONE NODE....WE CAN MOVE TO ANY OTHER NODES BCOZ ALL R IN CIRCLES....        LOSES: IN ORDER TO INSERT AN ELEMENT, THE TIME COMPLEXITY HERE IS "O(n)" WHEREAS IN CASE OF NORMALY SINGLY/DOUBLY... IT WAS "O(1)"

// CIRCULAR DOUBLY LINKED LIST : THE LAST NODE HAS ADDRESS OF THE FIRST NODE....AND AS U CAN GUESS THE FIRST NODE ALSO HAS THE ADDRESS OF THE LAST NODE :) COZ "DOUBLY" HAS ADDRESS OF BOTH ITS PREVIOUS AND NEXT NODE :)

