#include<iostream>
#include<cmath>
using namespace std;


int main(){
    int x=88;

    int* pt= &x;
    cout<< pt <<endl;     //POINTERS ARE REPRESENTED BY HEXADECIMAL NUMBERS IN C++,,, IN C IT WAS NORMAL DECIMAL :)
     

    pt=pt+1;                //WE KNOW EACH INTEGER IS OF "4-BITS" , AND "pt=pt+1" WILL TAKE IT TO THE ADDRESS OF THE NEXT INTEGER,,,(SINCE THIS INTEGER IS CONSUMING 4 BITS,,, THE NEXT INTEGER WILL BE "4-BITS" AHEAD OF THIS INTEGER,, AND HENCE WE WILL ADD 4 TO THE ADDRESS OF THIS INTEGER :)
    cout<< pt <<endl;       //REMEMBER: POINTERS ARE "HEXADECIMAL" NOS. , SO WHEN 4 IS ADDED, IT IS ADDED HEXADECIMALLY,(WHICH SOMETIMES MIGHT NOT FEEL INTEGRALLY SOUND) , HERE IT WENT FROM "8" TO "c"
    
    //NOTE: IN CASE OF POINTER OF "DOUBLE" , THE POINTER WILL MOVE "8-BITS" AHEAD ,BCOZ EACH DOUBLE IS OF 8 BITS, AND IT'S MOVING TO THE NEXT DOUBLE :)
    //IN CASE OF CHAR IT IS "1-BIT"

    double c=32.432;
    double* ptr = &c;
    cout<< ptr <<endl;
    ptr=ptr +1;
    cout<<ptr <<endl;


    //HOWEVER TAKING THE ADDRESS OF THE NEXT INTEGER ACTUALLY MAKES SENSE ONLY IN THE CASE OF ARRAYS, BCOZ AN ARRAY OF ELEMENTS ARE PLACED IN CONTINUOUS ADDRESSES;

    int arr[10];    //THIS BASICALLY HAS BOOKED 10X4 = 40 BITS, WHICH ARE CONSECUTIVE.
    cout<< sizeof(arr) <<endl;

    return 0;
}


