/*
    THESE NOTES START FROM "cr" IT INCLUDES NOTES FROM "CODE-WITH-HARRY"
    THEN I STARTED FOLLOWING CODING NINJAS :
    "cn" --> I STARTED WITH DSA COURSE OF CN , WHICH STARTED WITH POINTERS
    "cb" --> WHILE GOING DOWN THE LINE I REALISED, I SHOULD ALSO COMPLETE C++ INTRO COURSE , SO I STARTED "cb"(coding basics), HOWEVER AFTER COVERING BASICS, WE ALSO COVERED TOPICS LIKE QUICK-SORT AND MERGE-SORT :)
    
    IT IS NOT VERY ORGANISED BUT GOOD ENOUGH FOR REVISION
    SOME IMPORTANT NOTES ARE
    
    cn0.1_Char_basics.cpp
    cn0.2_STRINGS_basics.cpp
    
*/